name: Implementación en Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Implementar en Vercel
        uses: UnlyEd/github-action-deploy-on-vercel@latest
        with:
           command: "vercel --prod --token ${{ secrets.VERCEL_TOKEN }}"
        env:
           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      
