name: Implementación en Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Implementar en Vercel
        uses: UnlyEd/github-action-deploy-on-vercel@latest
        with:
           command: "vercel --prod --token ${{ secrets.VERCEL_TOKEN }}"
        env:
           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      - name: Download Phalcon Pecl Package
        uses: actions/download-artifact@v4
        with:
           name: phalcon-pecl
           path: ./phalcon-pecl
   
      - name: Build Phalcon Extension (Linux)
        uses: ./.github/actions/build-phalcon-linux
        if: runner.os == 'Linux'
        with:
           pecl: ./phalcon-pecl/phalcon-pecl.tgz
           php-version: ${{ matrix.php }}
   
      - name: Build Phalcon Extension (macOS)
        uses: ./.github/actions/build-phalcon-mac
        if: runner.os == 'macOS'
        with:
           pecl: ./phalcon-pecl/phalcon-pecl.tgz
   
      - name: Build Phalcon Extension (Windows)
        uses: ./.github/actions/build-phalcon-win
        if: runner.os == 'Windows'
        with:
           pecl: 'phalcon-pecl\phalcon-pecl.tgz'
           php_version: ${{ matrix.php }}
           ts: ${{ matrix.ts }}
           msvc: ${{ matrix.compiler }}
           arch: ${{ matrix.arch }}
           env:
             CACHE_DIR: 'C:\Downloads'
             TOOLS_DIR: ${{ env.TOOLS_DIR }}
   
      - name: Get Phalcon Extension path
        id: phalcon-ext-path
        shell: pwsh
        run: |
             if ( "${{ runner.os }}" -eq 'Windows' ) {
               $ReleaseFolder = if ("${{ matrix.ts }}" -eq "ts") { "Release_TS" } else { "Release" }
               $ReleaseFolder = if ("${{ matrix.arch }}" -eq "x64") { "x64\${ReleaseFolder}" } else { "${ReleaseFolder}" }
               $PhalconExtPath = "${{ env.TOOLS_DIR }}\pecl\phalcon\phalcon-${{ env.PHALCON_VERSION }}\${ReleaseFolder}\php_phalcon.dll"
             } else {
               $PhalconExtPath = "$(php-config --extension-dir)/phalcon.so"
             }
             echo "::set-output name=extension-path::$PhalconExtPath"
   #          echo "extension-path=$PhalconExtPath" >> "$GITHUB_OUTPUT"
   
      - name: Creates build artifact with Phalcon extension
        uses: ./.github/actions/pack-phalcon-ext
        with:
             target-name: phalcon-php${{ matrix.php }}-${{ matrix.ts }}-${{ matrix.name }}-${{ matrix.arch }}
             ext-path: ${{ steps.phalcon-ext-path.outputs.extension-path }}
   
